"use client";
import "./globals.css";
import type { Metadata } from "next";
import { createTheme } from "@/theme";
import { ThemeProvider, CssBaseline } from "@mui/material";

export const metadata: Metadata = {
  title: "Aggregate Table",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = createTheme();
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
